login_route:
    path:     /
    defaults: { _controller: MainBundle:Main:index }

login_check:
    path: /login_check

main_homepage:
    path:     /{page}
    defaults: { _controller: MainBundle:Main:index, page: null }

main_news:
    path:     /title/{news_title}
    defaults: { _controller: MainBundle:News:index }

main_test:
  path: /test
  defaults: {_controller: MainBundle:Default:test}

main_sending_post:
  path: /send/post
  defaults: { _controller: MainBundle:Main:post }