cabinet_detecting:
  path: /cabinet
  defaults: {_controller: CabinetBundle:Cabinet:index}
cabinet_pupil:
  path: /cabinet/pupil
  defaults: {_controller: CabinetBundle:Pupil:index}
cabinet_teacher:
  path: /cabinet/teacher
  defaults: {_controller: CabinetBundle:Teacher:index}
cabinet_boss:
  path: /cabinet/boss
  defaults: {_controller: CabinetBundle:Boss:index}
cabinet_food:
  path: /cabinet/food
  defaults: {_controller: CabinetBundle:Food:index}
cabinet_client:
  path: /cabinet/client
  defaults: {_controller: CabinetBundle:Client:index}


food_reports_mainmenu:
  path: /cabinet/food/report/mainmenu
  defaults: {_controller: CabinetBundle:Food:mainmenu}
food_zakaz_classes:
  path: /cabinet/food/report/classes
  defaults: {_controller: CabinetBundle:Food:classes}
food_reports_zakaz:
  path: /cabinet/food/report/zakaz
  defaults: {_controller: CabinetBundle:Food:zakaz}
food_reports_pitanie:
  path: /cabinet/food/report/pitanie
  defaults: {_controller: CabinetBundle:Food:pitanie}
food_pitanie_classes:
  path: /cabinet/food/report/classes
  defaults: {_controller: CabinetBundle:Food:classes}
food_rep_rep_1:
  path: /cabinet/food/report/pit/first
  defaults: {_controller: CabinetBundle:Food:first}
food_rep_rep_2:
  path: /cabinet/food/report/pit/second
  defaults: {_controller: CabinetBundle:Food:second}
food_rep_rep_3:
  path: /cabinet/food/report/pit/third
  defaults: {_controller: CabinetBundle:Food:third}
food_update_user_information:
  path: /cabinet/food/update/info
  defaults: {_controller: CabinetBundle:Cabinet:updateInfo}
food_update_photo:
  path: /cabinet/food/update/image
  defaults: {_controller: CabinetBundle:Cabinet:updateImage}

teacher_reports_mainmenu:
  path: /cabinet/teacher/report/mainmenu
  defaults: {_controller: CabinetBundle:Teacher:mainmenu}
teacher_reports_zakaz:
  path: /cabinet/teacher/report/zakaz
  defaults: {_controller: CabinetBundle:Teacher:zakaz}
teacher_reports_pitanie:
  path: /cabinet/teacher/report/pitanie
  defaults: {_controller: CabinetBundle:Teacher:pitanie}
teacher_reports_tabel:
  path: /cabinet/teacher/report/tabel
  defaults: {_controller: CabinetBundle:Teacher:tabel}
teacher_reports_list:
  path: /cabinet/teacher/report/list
  defaults: {_controller: CabinetBundle:Teacher:list}
teacher_reports_enter:
  path: /cabinet/teacher/report/enter
  defaults: {_controller: CabinetBundle:Teacher:enter}
teacher_update_user_information:
  path: /cabinet/teacher/update/info
  defaults: {_controller: CabinetBundle:Cabinet:updateInfo}
teacher_update_photo:
  path: /cabinet/teacher/update/image
  defaults: {_controller: CabinetBundle:Cabinet:updateImage}
teacher_reports_bal:
  path: /cabinet/teacher/report/balance
  defaults: {_controller: CabinetBundle:Teacher:balance}
teacher_change_bjt_flag:
  path: /cabinet/teacher/action/bjt
  defaults: {_controller: CabinetBundle:Teacher:changeBjt}

pupil_reports_mainmenu:
  path: /cabinet/pupil/report/menu
  defaults: {_controller: CabinetBundle:Pupil:menu}
pupil_reports_pitanie:
  path: /cabinet/pupil/report/pitanie
  defaults: {_controller: CabinetBundle:Pupil:pitanie}
pupil_reports_enter:
  path: /cabinet/pupil/report/enter
  defaults: {_controller: CabinetBundle:Pupil:enter}
pupil_reports_money:
  path: /cabinet/pupil/report/money
  defaults: {_controller: CabinetBundle:Pupil:money}
pupil_update_limit:
  path: /cabinet/pupil/update/limit
  defaults: {_controller: CabinetBundle:Pupil:updateLimit}
pupil_update_information:
  path: /cabinet/pupil/update/info
  defaults: {_controller: CabinetBundle:Pupil:updateInfo}
pupil_update_photo:
  path: /cabinet/pupil/update/image
  defaults: {_controller: CabinetBundle:Cabinet:updateImage}