cabinet_detecting:
  path: /cabinet
  defaults: {_controller: CabinetBundle:Cabinet:index}

cabinet_pupil:
  path: /cabinet/pupil
  defaults: {_controller: CabinetBundle:Pupil:index}

cabinet_teacher:
  path: /cabinet/teacher
  defaults: {_controller: CabinetBundle:Teacher:index}

cabinet_boss:
  path: /cabinet/boss
  defaults: {_controller: CabinetBundle:Boss:index}

cabinet_food:
  path: /cabinet/food
  defaults: {_controller: CabinetBundle:Food:index}

cabinet_client:
  path: /cabinet/client
  defaults: {_controller: CabinetBundle:Client:index}


food_reports_mainmenu:
  path: /cabinet/food/report/mainmenu
  defaults: {_controller: CabinetBundle:Food:mainmenu}

food_zakaz_classes:
  path: /cabinet/food/report/classes
  defaults: {_controller: CabinetBundle:Food:classes}
food_reports_zakaz:
  path: /cabinet/food/report/zakaz
  defaults: {_controller: CabinetBundle:Food:zakaz}

food_reports_pitanie:
  path: /cabinet/food/report/pitanie
  defaults: {_controller: CabinetBundle:Food:pitanie}
food_pitanie_classes:
  path: /cabinet/food/report/classes
  defaults: {_controller: CabinetBundle:Food:classes}

food_rep_pit1:
  path: /cabinet/food/report/pit/first
  defaults: {_controller: CabinetBundle:Food:first}